version: '3.8'
services:
  backend:
    build: .
    image: backend-image
    env_file:
      - .env
    depends_on:
      - elastic
      - redis
    restart: always
    expose:
      - 8000

  elastic:
    image: elasticsearch:8.7.0
    restart: unless-stopped
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: "-Xms600m -Xmx600m"
    expose:
      - 9200
    volumes:
      - elastic_volume:/usr/share/elasticsearch/data

  redis:
    image: redis:latest
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 6379

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
    depends_on:
      - backend
    ports:
      - "8000:80"
volumes:
  elastic_volume:
